2020-04-03 13:26:43,459 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-03 13:26:43,961 [ERROR]  Could not load model due to The model version is too old to be loaded by this Rasa NLU instance. Either retrain the model, or run with an older version. Model version: 1.8.2 Instance version: 1.9.3.
2020-04-03 13:26:43,962 [ERROR]  Experienced exception while trying to serve
Traceback (most recent call last):
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\sanic\app.py", line 1167, in run
    serve(**server_settings)
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\sanic\server.py", line 892, in serve
    trigger_events(before_start, loop)
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\sanic\server.py", line 668, in trigger_events
    loop.run_until_complete(result)
  File "c:\users\owner\appdata\local\programs\python\python36\lib\asyncio\base_events.py", line 484, in run_until_complete
    return future.result()
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\rasa\core\run.py", line 258, in load_agent_on_start
    action_endpoint=endpoints.action,
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\rasa\core\agent.py", line 271, in load_agent
    remote_storage=remote_storage,
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\rasa\core\agent.py", line 938, in load_local_model
    path_to_model_archive=model_archive,
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\rasa\core\agent.py", line 387, in load
    interpreter = NaturalLanguageInterpreter.create(nlu_model)
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\rasa\core\interpreter.py", line 54, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\rasa\core\interpreter.py", line 274, in __init__
    self._load_interpreter()
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\rasa\core\interpreter.py", line 297, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\rasa\nlu\model.py", line 300, in load
    Interpreter.ensure_model_compatibility(model_metadata)
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\rasa\nlu\model.py", line 275, in ensure_model_compatibility
    "".format(model_version, rasa.__version__)
rasa.nlu.model.UnsupportedModelError: The model version is too old to be loaded by this Rasa NLU instance. Either retrain the model, or run with an older version. Model version: 1.8.2 Instance version: 1.9.3
2020-04-03 13:29:50,463 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-03 13:29:50,969 [ERROR]  Could not load model due to The model version is too old to be loaded by this Rasa NLU instance. Either retrain the model, or run with an older version. Model version: 1.8.2 Instance version: 1.9.3.
2020-04-03 13:29:50,971 [ERROR]  Experienced exception while trying to serve
Traceback (most recent call last):
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\sanic\app.py", line 1167, in run
    serve(**server_settings)
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\sanic\server.py", line 892, in serve
    trigger_events(before_start, loop)
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\sanic\server.py", line 668, in trigger_events
    loop.run_until_complete(result)
  File "c:\users\owner\appdata\local\programs\python\python36\lib\asyncio\base_events.py", line 484, in run_until_complete
    return future.result()
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\rasa\core\run.py", line 258, in load_agent_on_start
    action_endpoint=endpoints.action,
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\rasa\core\agent.py", line 271, in load_agent
    remote_storage=remote_storage,
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\rasa\core\agent.py", line 938, in load_local_model
    path_to_model_archive=model_archive,
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\rasa\core\agent.py", line 387, in load
    interpreter = NaturalLanguageInterpreter.create(nlu_model)
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\rasa\core\interpreter.py", line 54, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\rasa\core\interpreter.py", line 274, in __init__
    self._load_interpreter()
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\rasa\core\interpreter.py", line 297, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\rasa\nlu\model.py", line 300, in load
    Interpreter.ensure_model_compatibility(model_metadata)
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\rasa\nlu\model.py", line 275, in ensure_model_compatibility
    "".format(model_version, rasa.__version__)
rasa.nlu.model.UnsupportedModelError: The model version is too old to be loaded by this Rasa NLU instance. Either retrain the model, or run with an older version. Model version: 1.8.2 Instance version: 1.9.3
2020-04-03 13:39:27,554 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-03 13:42:16,076 [ERROR]  Exception occurred while handling uri: unknown
NoneType: None
2020-04-03 13:54:26,276 [ERROR]  Exception occurred while handling uri: unknown
NoneType: None
2020-04-03 15:08:49,926 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-03 15:11:16,227 [ERROR]  Exception occurred while handling uri: unknown
NoneType: None
2020-04-03 15:20:44,795 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-03 15:21:58,102 [ERROR]  Exception occurred while handling uri: unknown
NoneType: None
2020-04-03 15:21:58,370 [ERROR]  Exception occurred while handling uri: unknown
NoneType: None
2020-04-03 15:22:07,450 [ERROR]  Exception occurred while handling uri: unknown
NoneType: None
2020-04-03 15:57:43,308 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-03 16:00:11,731 [ERROR]  The model predicted the custom action 'action_faq_qa_model', but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration via the --endpoints flag. https://rasa.com/docs/rasa/core/actions
2020-04-03 16:00:11,733 [ERROR]  Encountered an exception while running action 'action_faq_qa_model'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-04-03 16:00:37,659 [ERROR]  The model predicted the custom action 'action_faq_qa_model', but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration via the --endpoints flag. https://rasa.com/docs/rasa/core/actions
2020-04-03 16:00:37,662 [ERROR]  Encountered an exception while running action 'action_faq_qa_model'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-04-03 16:02:37,188 [ERROR]  The model predicted the custom action 'action_faq_qa_model', but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration via the --endpoints flag. https://rasa.com/docs/rasa/core/actions
2020-04-03 16:02:37,190 [ERROR]  Encountered an exception while running action 'action_faq_qa_model'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-04-03 16:03:37,378 [ERROR]  Exception occurred while handling uri: unknown
NoneType: None
2020-04-03 16:27:23,541 [ERROR]  Exception occurred while handling uri: unknown
NoneType: None
2020-04-03 16:36:02,709 [ERROR]  The model predicted the custom action 'action_faq_qa_model', but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration via the --endpoints flag. https://rasa.com/docs/rasa/core/actions
2020-04-03 16:36:02,711 [ERROR]  Encountered an exception while running action 'action_faq_qa_model'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-04-03 16:38:56,607 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-03 16:40:36,210 [ERROR]  Encountered an exception while running action 'action_faq_qa_model'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-04-03 16:42:48,919 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-03 16:43:11,845 [ERROR]  Encountered an exception while running action 'action_faq_qa_model'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-04-03 16:50:15,672 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-03 16:50:55,488 [ERROR]  Encountered an exception while running action 'action_faq_qa_model'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-04-03 16:51:53,668 [ERROR]  Exception occurred while handling uri: unknown
NoneType: None
2020-04-03 16:52:36,858 [ERROR]  Encountered an exception while running action 'action_faq_qa_model'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-04-03 16:53:14,778 [ERROR]  Exception occurred while handling uri: unknown
NoneType: None
2020-04-03 16:57:15,236 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-03 17:10:53,808 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-03 17:12:23,759 [ERROR]  Exception occurred while handling uri: unknown
NoneType: None
2020-04-03 17:44:28,503 [ERROR]  Exception occurred while handling uri: unknown
NoneType: None
2020-04-03 21:17:41,615 [ERROR]  Exception occurred while handling uri: unknown
NoneType: None
2020-04-03 21:17:41,870 [ERROR]  Exception occurred while handling uri: unknown
NoneType: None
2020-04-03 21:26:24,831 [ERROR]  Exception occurred while handling uri: unknown
NoneType: None
2020-04-03 21:26:25,091 [ERROR]  Exception occurred while handling uri: unknown
NoneType: None
2020-04-03 22:31:17,065 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-03 22:32:32,404 [ERROR]  Exception occurred while handling uri: unknown
NoneType: None
2020-04-03 22:32:32,652 [ERROR]  Exception occurred while handling uri: unknown
NoneType: None
2020-04-03 22:36:53,831 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-03 22:43:20,435 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-03 22:44:05,466 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-17 13:23:55,962 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-17 13:25:37,916 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-17 13:34:21,525 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/favicon.ico'
Traceback (most recent call last):
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/sanic/app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/sanic/router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/sanic/router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /favicon.ico not found
2020-04-17 13:40:54,419 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-17 13:43:45,191 [INFO ]  Killing Sanic server now.
2020-04-17 13:48:28,996 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-17 13:50:54,834 [INFO ]  Killing Sanic server now.
2020-04-17 13:52:05,990 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_events
/webhooks/rest                                     GET                            custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_CmdlineInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/conversations/<conversation_id>/trigger_intent    POST                           trigger_intent
/model                                             DELETE                         unload_model
/version                                           GET                            version
2020-04-17 13:52:05,990 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-17 13:52:05,991 [DEBUG]  Using the default number of Sanic workers (1).
2020-04-17 13:52:05,992 [INFO ]  Enabling coroutine debugging. Loop id 94704978367488.
2020-04-17 13:52:06,490 [DEBUG]  Extracted model to '/tmp/tmp1yzjg5hv'.
2020-04-17 13:52:07,294 [DEBUG]  Loading the model ...
2020-04-17 13:52:08,605 [DEBUG]  Finished loading the model.
2020-04-17 13:52:08,606 [DEBUG]  Building tensorflow prediction graph...
2020-04-17 13:52:15,135 [DEBUG]  Finished building tensorflow prediction graph.
2020-04-17 13:52:15,137 [DEBUG]  Failed to load model for 'ResponseSelector'. Maybe you did not provide enough training data and no model was trained or the path '/tmp/tmp1yzjg5hv/nlu' doesn't exist?
2020-04-17 13:52:15,148 [DEBUG]  Connected to InMemoryTrackerStore.
2020-04-17 13:52:15,148 [DEBUG]  Connected to lock store 'InMemoryLockStore'.
2020-04-17 13:52:15,440 [DEBUG]  Extracted model to '/tmp/tmp0v5m4h8y'.
2020-04-17 13:52:15,445 [DEBUG]  Using yaml library: /media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/ruamel/yaml/__init__.py
2020-04-17 13:52:15,485 [DEBUG]  Loading the model ...
2020-04-17 13:52:15,769 [DEBUG]  Finished loading the model.
2020-04-17 13:52:15,769 [DEBUG]  Building tensorflow prediction graph...
2020-04-17 13:52:16,688 [DEBUG]  Finished building tensorflow prediction graph.
2020-04-17 13:52:16,694 [DEBUG]  Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
2020-04-17 13:55:56,689 [INFO ]  Killing Sanic server now.
2020-04-17 13:56:19,742 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-17 13:57:19,623 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/conversations/1/messages'
Traceback (most recent call last):
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/sanic/app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/sanic/router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/sanic/router.py", line 474, in _get
    raise method_not_supported
sanic.exceptions.MethodNotSupported: Method GET not allowed for URL /conversations/1/messages
2020-04-17 13:58:03,401 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-17 14:29:35,840 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/http://localhost:5005/webhooks/rest/webhook'
Traceback (most recent call last):
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/sanic/app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/sanic/router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/sanic/router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /http://localhost:5005/webhooks/rest/webhook not found
2020-04-17 14:36:40,502 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/webhooks'
Traceback (most recent call last):
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/sanic/app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/sanic/router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/sanic/router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /webhooks not found
2020-04-17 14:36:56,195 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/webhooks/rest/webhook'
Traceback (most recent call last):
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/sanic/app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/sanic/router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/sanic/router.py", line 452, in _get
    raise method_not_supported
sanic.exceptions.MethodNotSupported: Method GET not allowed for URL /webhooks/rest/webhook
2020-04-17 14:39:04,034 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-17 14:46:35,931 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_events
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/conversations/<conversation_id>/trigger_intent    POST                           trigger_intent
/model                                             DELETE                         unload_model
/version                                           GET                            version
2020-04-17 14:46:35,959 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-17 14:46:36,003 [DEBUG]  Using the default number of Sanic workers (1).
2020-04-17 14:46:36,011 [INFO ]  Enabling coroutine debugging. Loop id 94275454543808.
2020-04-17 14:46:36,417 [DEBUG]  Extracted model to '/tmp/tmp1zc12k27'.
2020-04-17 14:46:40,794 [DEBUG]  Loading the model ...
2020-04-17 14:46:42,779 [DEBUG]  Finished loading the model.
2020-04-17 14:46:42,779 [DEBUG]  Building tensorflow prediction graph...
2020-04-17 14:46:49,063 [DEBUG]  Finished building tensorflow prediction graph.
2020-04-17 14:46:49,065 [DEBUG]  Failed to load model for 'ResponseSelector'. Maybe you did not provide enough training data and no model was trained or the path '/tmp/tmp1zc12k27/nlu' doesn't exist?
2020-04-17 14:46:49,075 [DEBUG]  Connected to InMemoryTrackerStore.
2020-04-17 14:46:49,075 [DEBUG]  Connected to lock store 'InMemoryLockStore'.
2020-04-17 14:46:49,398 [DEBUG]  Extracted model to '/tmp/tmpev74jsq1'.
2020-04-17 14:46:49,477 [DEBUG]  Using yaml library: /media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/ruamel/yaml/__init__.py
2020-04-17 14:46:49,655 [DEBUG]  Loading the model ...
2020-04-17 14:46:50,012 [DEBUG]  Finished loading the model.
2020-04-17 14:46:50,013 [DEBUG]  Building tensorflow prediction graph...
2020-04-17 14:46:51,031 [DEBUG]  Finished building tensorflow prediction graph.
2020-04-17 14:46:51,122 [DEBUG]  Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
2020-04-17 14:47:58,043 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/webhooks/rasa/webhook'
Traceback (most recent call last):
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/sanic/app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/sanic/router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/sanic/router.py", line 452, in _get
    raise method_not_supported
sanic.exceptions.MethodNotSupported: Method GET not allowed for URL /webhooks/rasa/webhook
2020-04-17 14:48:08,835 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/webhooks/rasa/webhook'
Traceback (most recent call last):
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "uvloop/loop.pyx", line 1974, in create_connection
  File "uvloop/loop.pyx", line 1951, in uvloop.loop.Loop.create_connection
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/sanic/app.py", line 976, in handle_request
    response = await response
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/rasa/core/channels/channel.py", line 462, in receive
    sender_id = await self._extract_sender(request)
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/rasa/core/channels/rasa_chat.py", line 102, in _extract_sender
    jwt_payload = await self._decode_bearer_token(req.args.get("token"))
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/rasa/core/channels/rasa_chat.py", line 82, in _decode_bearer_token
    await self._fetch_public_key()
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/rasa/core/channels/rasa_chat.py", line 44, in _fetch_public_key
    public_key_url, timeout=DEFAULT_REQUEST_TIMEOUT
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:5002 ssl:default [Connection refused]
2020-04-17 14:48:17,606 [DEBUG]  Creating a new tracker for id 'ak'.
2020-04-17 14:48:17,607 [DEBUG]  Starting a new session for conversation ID 'ak'.
2020-04-17 14:48:17,607 [DEBUG]  Action 'action_session_start' ended with events '[<rasa.core.events.SessionStarted object at 0x7f01581d58d0>, <rasa.core.events.ActionExecuted object at 0x7f0158209150>]'.
2020-04-17 14:48:18,133 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-17 14:48:18,134 [DEBUG]  Adding following selector key to message property: default
2020-04-17 14:48:18,134 [DEBUG]  Received user message 'what is RWDS' with intent '{'name': 'affirm', 'confidence': 0.7330762147903442}' and entities '[]'
2020-04-17 14:48:18,135 [DEBUG]  Logged UserUtterance - tracker now has 4 events.
2020-04-17 14:48:18,137 [DEBUG]  Current tracker state [None, None, None, {}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}]
2020-04-17 14:48:18,138 [DEBUG]  There is no memorised next action
2020-04-17 14:48:18,142 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-04-17 14:48:18,142 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-17 14:48:18,143 [DEBUG]  Predicted next action 'utter_happy' with confidence 0.95.
2020-04-17 14:48:18,144 [DEBUG]  Action 'utter_happy' ended with events '[BotUttered('Great, carry on!', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1587127698.1446276)]'.
2020-04-17 14:48:18,145 [DEBUG]  Current tracker state [None, None, {}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_utter_happy': 1.0, 'intent_affirm': 1.0}]
2020-04-17 14:48:18,145 [DEBUG]  There is no memorised next action
2020-04-17 14:48:18,151 [DEBUG]  There is no mapped action for the predicted intent, 'affirm'.
2020-04-17 14:48:18,152 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-04-17 14:48:18,153 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-17 14:48:18,153 [DEBUG]  Predicted next action 'action_listen' with confidence 0.96.
2020-04-17 14:48:18,153 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-17 14:48:18,155 [DEBUG]  Deleted lock for conversation 'ak'.
2020-04-17 14:48:50,638 [DEBUG]  Recreating tracker for id 'ak'
2020-04-17 14:48:50,650 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-17 14:48:50,650 [DEBUG]  Adding following selector key to message property: default
2020-04-17 14:48:50,651 [DEBUG]  Received user message 'what is RWDS' with intent '{'name': 'affirm', 'confidence': 0.7330762147903442}' and entities '[]'
2020-04-17 14:48:50,652 [DEBUG]  Logged UserUtterance - tracker now has 8 events.
2020-04-17 14:48:50,653 [DEBUG]  Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_utter_happy': 1.0, 'intent_affirm': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}]
2020-04-17 14:48:50,653 [DEBUG]  There is no memorised next action
2020-04-17 14:48:50,657 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-04-17 14:48:50,657 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-17 14:48:50,657 [DEBUG]  Predicted next action 'utter_happy' with confidence 0.96.
2020-04-17 14:48:50,658 [DEBUG]  Action 'utter_happy' ended with events '[BotUttered('Great, carry on!', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1587127730.6581395)]'.
2020-04-17 14:48:50,658 [DEBUG]  Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_utter_happy': 1.0, 'intent_affirm': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_utter_happy': 1.0, 'intent_affirm': 1.0}]
2020-04-17 14:48:50,659 [DEBUG]  There is no memorised next action
2020-04-17 14:48:50,662 [DEBUG]  There is no mapped action for the predicted intent, 'affirm'.
2020-04-17 14:48:50,662 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-04-17 14:48:50,662 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-17 14:48:50,663 [DEBUG]  Predicted next action 'action_listen' with confidence 0.96.
2020-04-17 14:48:50,663 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-17 14:48:50,664 [DEBUG]  Deleted lock for conversation 'ak'.
2020-04-17 14:48:58,924 [DEBUG]  Recreating tracker for id 'ak'
2020-04-17 14:48:58,935 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-17 14:48:58,935 [DEBUG]  Adding following selector key to message property: default
2020-04-17 14:48:58,936 [DEBUG]  Received user message 'hello' with intent '{'name': 'greet', 'confidence': 0.9974324107170105}' and entities '[]'
2020-04-17 14:48:58,936 [DEBUG]  Logged UserUtterance - tracker now has 12 events.
2020-04-17 14:48:58,937 [DEBUG]  Current tracker state [{'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_utter_happy': 1.0, 'intent_affirm': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_utter_happy': 1.0, 'intent_affirm': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
2020-04-17 14:48:58,938 [DEBUG]  There is no memorised next action
2020-04-17 14:48:58,941 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-04-17 14:48:58,942 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-17 14:48:58,942 [DEBUG]  Predicted next action 'utter_greet' with confidence 0.96.
2020-04-17 14:48:58,942 [DEBUG]  Action 'utter_greet' ended with events '[BotUttered('Hey! How are you?', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1587127738.942805)]'.
2020-04-17 14:48:58,943 [DEBUG]  Current tracker state [{'prev_utter_happy': 1.0, 'intent_affirm': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_utter_happy': 1.0, 'intent_affirm': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}]
2020-04-17 14:48:58,944 [DEBUG]  There is no memorised next action
2020-04-17 14:48:58,947 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2020-04-17 14:48:58,948 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-04-17 14:48:58,948 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-17 14:48:58,948 [DEBUG]  Predicted next action 'action_listen' with confidence 0.96.
2020-04-17 14:48:58,949 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-17 14:48:58,951 [DEBUG]  Deleted lock for conversation 'ak'.
2020-04-17 14:57:31,164 [DEBUG]  Creating a new tracker for id 'a78ef04e-ecca-49b5-a092-88b53ae462bf'.
2020-04-17 14:57:31,165 [DEBUG]  Starting a new session for conversation ID 'a78ef04e-ecca-49b5-a092-88b53ae462bf'.
2020-04-17 14:57:31,165 [DEBUG]  Action 'action_session_start' ended with events '[<rasa.core.events.SessionStarted object at 0x7f01580bb510>, <rasa.core.events.ActionExecuted object at 0x7f01580bb650>]'.
2020-04-17 14:57:33,317 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-17 14:57:33,317 [DEBUG]  Adding following selector key to message property: default
2020-04-17 14:57:33,317 [DEBUG]  Received user message 'how does hyperbus master begin a transaction?' with intent '{'name': 'deny', 'confidence': 0.38151395320892334}' and entities '[]'
2020-04-17 14:57:33,318 [DEBUG]  Logged UserUtterance - tracker now has 4 events.
2020-04-17 14:57:33,319 [DEBUG]  Current tracker state [None, None, None, {}, {'intent_deny': 1.0, 'prev_action_listen': 1.0}]
2020-04-17 14:57:33,320 [DEBUG]  There is no memorised next action
2020-04-17 14:57:33,323 [DEBUG]  NLU confidence 0.38151395320892334 is lower than NLU threshold 0.40. 
2020-04-17 14:57:33,323 [DEBUG]  Predicted next action using policy_3_FallbackPolicy
2020-04-17 14:57:33,323 [DEBUG]  Predicted next action 'action_faq_qa_model' with confidence 1.00.
2020-04-17 14:57:33,324 [DEBUG]  Calling action endpoint to run action 'action_faq_qa_model'.
2020-04-17 14:57:41,848 [DEBUG]  Action 'action_faq_qa_model' ended with events '[BotUttered('by driving CS# Low while clock is idle', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1587128261.848691), <rasa.core.events.UserUtteranceReverted object at 0x7f01580ac650>]'.
2020-04-17 14:57:41,849 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2020-04-17 14:57:41,849 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-17 14:57:41,849 [DEBUG]  Deleted lock for conversation 'a78ef04e-ecca-49b5-a092-88b53ae462bf'.
2020-04-17 14:59:17,706 [DEBUG]  Recreating tracker for id 'a78ef04e-ecca-49b5-a092-88b53ae462bf'
2020-04-17 14:59:17,734 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-17 14:59:17,735 [DEBUG]  Adding following selector key to message property: default
2020-04-17 14:59:17,735 [DEBUG]  Received user message 'what is RWDS of hyperbus' with intent '{'name': 'affirm', 'confidence': 0.6463959813117981}' and entities '[]'
2020-04-17 14:59:17,735 [DEBUG]  Logged UserUtterance - tracker now has 9 events.
2020-04-17 14:59:17,736 [DEBUG]  Current tracker state [None, None, None, {}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}]
2020-04-17 14:59:17,736 [DEBUG]  There is no memorised next action
2020-04-17 14:59:17,739 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-04-17 14:59:17,741 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-17 14:59:17,742 [DEBUG]  Predicted next action 'utter_happy' with confidence 0.95.
2020-04-17 14:59:17,743 [DEBUG]  Action 'utter_happy' ended with events '[BotUttered('Great, carry on!', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1587128357.7431338)]'.
2020-04-17 14:59:17,745 [DEBUG]  Current tracker state [None, None, {}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_utter_happy': 1.0, 'intent_affirm': 1.0}]
2020-04-17 14:59:17,746 [DEBUG]  There is no memorised next action
2020-04-17 14:59:17,761 [DEBUG]  There is no mapped action for the predicted intent, 'affirm'.
2020-04-17 14:59:17,762 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-04-17 14:59:17,762 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-17 14:59:17,763 [DEBUG]  Predicted next action 'action_listen' with confidence 0.96.
2020-04-17 14:59:17,763 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-17 14:59:17,765 [DEBUG]  Deleted lock for conversation 'a78ef04e-ecca-49b5-a092-88b53ae462bf'.
2020-04-17 14:59:30,040 [DEBUG]  Recreating tracker for id 'a78ef04e-ecca-49b5-a092-88b53ae462bf'
2020-04-17 14:59:30,053 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-17 14:59:30,053 [DEBUG]  Adding following selector key to message property: default
2020-04-17 14:59:30,054 [DEBUG]  Received user message 'what is RWDS of hyperbus protocol' with intent '{'name': 'affirm', 'confidence': 0.521808922290802}' and entities '[]'
2020-04-17 14:59:30,056 [DEBUG]  Logged UserUtterance - tracker now has 13 events.
2020-04-17 14:59:30,057 [DEBUG]  Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_utter_happy': 1.0, 'intent_affirm': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}]
2020-04-17 14:59:30,058 [DEBUG]  There is no memorised next action
2020-04-17 14:59:30,062 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-04-17 14:59:30,063 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-17 14:59:30,063 [DEBUG]  Predicted next action 'utter_happy' with confidence 0.96.
2020-04-17 14:59:30,067 [DEBUG]  Action 'utter_happy' ended with events '[BotUttered('Great, carry on!', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1587128370.0668344)]'.
2020-04-17 14:59:30,068 [DEBUG]  Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_utter_happy': 1.0, 'intent_affirm': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_utter_happy': 1.0, 'intent_affirm': 1.0}]
2020-04-17 14:59:30,068 [DEBUG]  There is no memorised next action
2020-04-17 14:59:30,076 [DEBUG]  There is no mapped action for the predicted intent, 'affirm'.
2020-04-17 14:59:30,077 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-04-17 14:59:30,077 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-17 14:59:30,078 [DEBUG]  Predicted next action 'action_listen' with confidence 0.96.
2020-04-17 14:59:30,078 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-17 14:59:30,079 [DEBUG]  Deleted lock for conversation 'a78ef04e-ecca-49b5-a092-88b53ae462bf'.
2020-04-17 16:39:54,872 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_events
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/conversations/<conversation_id>/trigger_intent    POST                           trigger_intent
/model                                             DELETE                         unload_model
/version                                           GET                            version
2020-04-17 16:39:54,962 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-17 16:39:54,964 [DEBUG]  Using the default number of Sanic workers (1).
2020-04-17 16:39:54,965 [INFO ]  Enabling coroutine debugging. Loop id 94311332075232.
2020-04-17 16:39:57,645 [DEBUG]  Extracted model to '/tmp/tmp_d41aegs'.
2020-04-17 16:40:08,867 [DEBUG]  Loading the model ...
2020-04-17 16:40:18,251 [DEBUG]  Finished loading the model.
2020-04-17 16:40:18,274 [DEBUG]  Building tensorflow prediction graph...
2020-04-17 16:40:33,781 [DEBUG]  Finished building tensorflow prediction graph.
2020-04-17 16:40:33,783 [DEBUG]  Failed to load model for 'ResponseSelector'. Maybe you did not provide enough training data and no model was trained or the path '/tmp/tmp_d41aegs/nlu' doesn't exist?
2020-04-17 16:40:33,836 [DEBUG]  Connected to InMemoryTrackerStore.
2020-04-17 16:40:33,837 [DEBUG]  Connected to lock store 'InMemoryLockStore'.
2020-04-17 16:40:34,211 [DEBUG]  Extracted model to '/tmp/tmphix_ltgg'.
2020-04-17 16:40:34,324 [DEBUG]  Using yaml library: /media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/ruamel/yaml/__init__.py
2020-04-17 16:40:34,526 [DEBUG]  Loading the model ...
2020-04-17 16:40:34,991 [DEBUG]  Finished loading the model.
2020-04-17 16:40:34,992 [DEBUG]  Building tensorflow prediction graph...
2020-04-17 16:40:35,946 [DEBUG]  Finished building tensorflow prediction graph.
2020-04-17 16:40:36,001 [DEBUG]  Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
2020-04-17 16:42:15,192 [DEBUG]  Creating a new tracker for id 'ak'.
2020-04-17 16:42:15,193 [DEBUG]  Starting a new session for conversation ID 'ak'.
2020-04-17 16:42:15,193 [DEBUG]  Action 'action_session_start' ended with events '[<rasa.core.events.SessionStarted object at 0x7f499a69d690>, <rasa.core.events.ActionExecuted object at 0x7f499a69d650>]'.
2020-04-17 16:42:15,726 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-17 16:42:15,727 [DEBUG]  Adding following selector key to message property: default
2020-04-17 16:42:15,727 [DEBUG]  Received user message 'hello' with intent '{'name': 'greet', 'confidence': 0.9974324107170105}' and entities '[]'
2020-04-17 16:42:15,727 [DEBUG]  Logged UserUtterance - tracker now has 4 events.
2020-04-17 16:42:15,728 [DEBUG]  Current tracker state [None, None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
2020-04-17 16:42:15,728 [DEBUG]  There is a memorised next action 'utter_greet'
2020-04-17 16:42:15,734 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-04-17 16:42:15,760 [DEBUG]  Predicted next action using policy_0_MemoizationPolicy
2020-04-17 16:42:15,761 [DEBUG]  Predicted next action 'utter_greet' with confidence 1.00.
2020-04-17 16:42:15,763 [DEBUG]  Action 'utter_greet' ended with events '[BotUttered('Hey! How are you?', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1587134535.763762)]'.
2020-04-17 16:42:15,764 [DEBUG]  Current tracker state [None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}]
2020-04-17 16:42:15,765 [DEBUG]  There is a memorised next action 'action_listen'
2020-04-17 16:42:15,772 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2020-04-17 16:42:15,773 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-04-17 16:42:15,773 [DEBUG]  Predicted next action using policy_0_MemoizationPolicy
2020-04-17 16:42:15,774 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2020-04-17 16:42:15,775 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-17 16:42:15,776 [DEBUG]  Deleted lock for conversation 'ak'.
2020-04-17 16:42:40,028 [DEBUG]  Recreating tracker for id 'ak'
2020-04-17 16:42:40,325 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-17 16:42:40,326 [DEBUG]  Adding following selector key to message property: default
2020-04-17 16:42:40,326 [DEBUG]  Received user message 'how does hyperbus master begin a transaction?' with intent '{'name': 'deny', 'confidence': 0.38151395320892334}' and entities '[]'
2020-04-17 16:42:40,327 [DEBUG]  Logged UserUtterance - tracker now has 8 events.
2020-04-17 16:42:40,329 [DEBUG]  Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_deny': 1.0}]
2020-04-17 16:42:40,329 [DEBUG]  There is no memorised next action
2020-04-17 16:42:40,334 [DEBUG]  NLU confidence 0.38151395320892334 is lower than NLU threshold 0.40. 
2020-04-17 16:42:40,335 [DEBUG]  Predicted next action using policy_3_FallbackPolicy
2020-04-17 16:42:40,336 [DEBUG]  Predicted next action 'action_faq_qa_model' with confidence 1.00.
2020-04-17 16:42:40,336 [DEBUG]  Calling action endpoint to run action 'action_faq_qa_model'.
2020-04-17 16:42:40,663 [ERROR]  Failed to run custom action 'action_faq_qa_model'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: Cannot connect to host localhost:5055 ssl:default [Connection refused]
2020-04-17 16:42:40,664 [ERROR]  Encountered an exception while running action 'action_faq_qa_model'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-04-17 16:42:40,664 [DEBUG]  Failed to execute custom action.
Traceback (most recent call last):
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "uvloop/loop.pyx", line 1974, in create_connection
  File "uvloop/loop.pyx", line 1951, in uvloop.loop.Loop.create_connection
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/rasa/core/actions/action.py", line 549, in run
    json=json_body, method="post", timeout=DEFAULT_REQUEST_TIMEOUT
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/rasa/utils/endpoints.py", line 146, in request
    **kwargs,
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:5055 ssl:default [Connection refused]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/rasa/core/processor.py", line 630, in _run_action
    events = await action.run(output_channel, nlg, tracker, self.domain)
  File "/media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/rasa/core/actions/action.py", line 580, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
2020-04-17 16:42:40,666 [DEBUG]  Action 'action_faq_qa_model' ended with events '[]'.
2020-04-17 16:42:40,666 [DEBUG]  Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_deny': 1.0}, {'prev_action_faq_qa_model': 1.0, 'intent_deny': 1.0}]
2020-04-17 16:42:40,667 [DEBUG]  There is no memorised next action
2020-04-17 16:42:40,671 [DEBUG]  There is no mapped action for the predicted intent, 'deny'.
2020-04-17 16:42:40,671 [DEBUG]  Predicted 'action_listen' after fallback action 'action_faq_qa_model'
2020-04-17 16:42:40,672 [DEBUG]  Predicted next action using policy_3_FallbackPolicy
2020-04-17 16:42:40,672 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2020-04-17 16:42:40,672 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-17 16:42:40,674 [DEBUG]  Deleted lock for conversation 'ak'.
2020-04-17 18:13:32,525 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_events
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/conversations/<conversation_id>/trigger_intent    POST                           trigger_intent
/model                                             DELETE                         unload_model
/version                                           GET                            version
2020-04-17 18:13:32,575 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-17 18:13:32,576 [DEBUG]  Using the default number of Sanic workers (1).
2020-04-17 18:13:32,726 [INFO ]  Enabling coroutine debugging. Loop id 94154894674176.
2020-04-17 18:13:33,321 [DEBUG]  Extracted model to '/tmp/tmpzw55i41i'.
2020-04-17 18:13:41,233 [DEBUG]  Loading the model ...
2020-04-17 18:13:51,744 [DEBUG]  Finished loading the model.
2020-04-17 18:13:51,745 [DEBUG]  Building tensorflow prediction graph...
2020-04-17 18:14:04,918 [DEBUG]  Finished building tensorflow prediction graph.
2020-04-17 18:14:04,933 [DEBUG]  Failed to load model for 'ResponseSelector'. Maybe you did not provide enough training data and no model was trained or the path '/tmp/tmpzw55i41i/nlu' doesn't exist?
2020-04-17 18:14:04,943 [DEBUG]  Connected to InMemoryTrackerStore.
2020-04-17 18:14:04,961 [DEBUG]  Connected to lock store 'InMemoryLockStore'.
2020-04-17 18:14:05,658 [DEBUG]  Extracted model to '/tmp/tmpegq86d42'.
2020-04-17 18:14:05,804 [DEBUG]  Using yaml library: /media/ak/storage3/qa-system/venv/lib/python3.7/site-packages/ruamel/yaml/__init__.py
2020-04-17 18:14:06,139 [DEBUG]  Loading the model ...
2020-04-17 18:14:06,842 [DEBUG]  Finished loading the model.
2020-04-17 18:14:06,843 [DEBUG]  Building tensorflow prediction graph...
2020-04-17 18:14:08,686 [DEBUG]  Finished building tensorflow prediction graph.
2020-04-17 18:14:08,771 [DEBUG]  Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
2020-04-17 18:14:28,515 [DEBUG]  Creating a new tracker for id 'ak'.
2020-04-17 18:14:28,517 [DEBUG]  Starting a new session for conversation ID 'ak'.
2020-04-17 18:14:28,517 [DEBUG]  Action 'action_session_start' ended with events '[<rasa.core.events.SessionStarted object at 0x7eff00554fd0>, <rasa.core.events.ActionExecuted object at 0x7eff0063d650>]'.
2020-04-17 18:14:29,613 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-17 18:14:29,613 [DEBUG]  Adding following selector key to message property: default
2020-04-17 18:14:29,614 [DEBUG]  Received user message 'how does hyperbus master begin a transaction?' with intent '{'name': 'deny', 'confidence': 0.38151395320892334}' and entities '[]'
2020-04-17 18:14:29,616 [DEBUG]  Logged UserUtterance - tracker now has 4 events.
2020-04-17 18:14:29,617 [DEBUG]  Current tracker state [None, None, None, {}, {'intent_deny': 1.0, 'prev_action_listen': 1.0}]
2020-04-17 18:14:29,618 [DEBUG]  There is no memorised next action
2020-04-17 18:14:29,761 [DEBUG]  NLU confidence 0.38151395320892334 is lower than NLU threshold 0.40. 
2020-04-17 18:14:29,761 [DEBUG]  Predicted next action using policy_3_FallbackPolicy
2020-04-17 18:14:29,762 [DEBUG]  Predicted next action 'action_faq_qa_model' with confidence 1.00.
2020-04-17 18:14:29,763 [DEBUG]  Calling action endpoint to run action 'action_faq_qa_model'.
2020-04-17 18:14:41,835 [DEBUG]  Action 'action_faq_qa_model' ended with events '[BotUttered('by driving CS# Low while clock is idle', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1587140081.8350494), <rasa.core.events.UserUtteranceReverted object at 0x7eff00492450>]'.
2020-04-17 18:14:41,857 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2020-04-17 18:14:41,881 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-17 18:14:41,883 [DEBUG]  Deleted lock for conversation 'ak'.
2020-04-17 18:14:48,028 [DEBUG]  Recreating tracker for id 'ak'
2020-04-17 18:14:48,052 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-17 18:14:48,053 [DEBUG]  Adding following selector key to message property: default
2020-04-17 18:14:48,057 [DEBUG]  Received user message 'how does hyperbus master begin a transaction?' with intent '{'name': 'deny', 'confidence': 0.38151395320892334}' and entities '[]'
2020-04-17 18:14:48,060 [DEBUG]  Logged UserUtterance - tracker now has 9 events.
2020-04-17 18:14:48,062 [DEBUG]  Current tracker state [None, None, None, {}, {'intent_deny': 1.0, 'prev_action_listen': 1.0}]
2020-04-17 18:14:48,062 [DEBUG]  There is no memorised next action
2020-04-17 18:14:48,070 [DEBUG]  NLU confidence 0.38151395320892334 is lower than NLU threshold 0.40. 
2020-04-17 18:14:48,073 [DEBUG]  Predicted next action using policy_3_FallbackPolicy
2020-04-17 18:14:48,074 [DEBUG]  Predicted next action 'action_faq_qa_model' with confidence 1.00.
2020-04-17 18:14:48,075 [DEBUG]  Calling action endpoint to run action 'action_faq_qa_model'.
2020-04-17 18:14:53,859 [DEBUG]  Action 'action_faq_qa_model' ended with events '[BotUttered('by driving CS# Low while clock is idle', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1587140093.85933), <rasa.core.events.UserUtteranceReverted object at 0x7eff00554710>]'.
2020-04-17 18:14:53,863 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2020-04-17 18:14:53,865 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-17 18:14:53,867 [DEBUG]  Deleted lock for conversation 'ak'.
2020-04-17 18:14:57,358 [DEBUG]  Recreating tracker for id 'ak'
2020-04-17 18:14:57,388 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-17 18:14:57,389 [DEBUG]  Adding following selector key to message property: default
2020-04-17 18:14:57,389 [DEBUG]  Received user message 'how does hyperbus master begin a transaction?' with intent '{'name': 'deny', 'confidence': 0.38151395320892334}' and entities '[]'
2020-04-17 18:14:57,390 [DEBUG]  Logged UserUtterance - tracker now has 14 events.
2020-04-17 18:14:57,391 [DEBUG]  Current tracker state [None, None, None, {}, {'intent_deny': 1.0, 'prev_action_listen': 1.0}]
2020-04-17 18:14:57,393 [DEBUG]  There is no memorised next action
2020-04-17 18:14:57,405 [DEBUG]  NLU confidence 0.38151395320892334 is lower than NLU threshold 0.40. 
2020-04-17 18:14:57,408 [DEBUG]  Predicted next action using policy_3_FallbackPolicy
2020-04-17 18:14:57,413 [DEBUG]  Predicted next action 'action_faq_qa_model' with confidence 1.00.
2020-04-17 18:14:57,416 [DEBUG]  Calling action endpoint to run action 'action_faq_qa_model'.
2020-04-17 18:15:03,220 [DEBUG]  Action 'action_faq_qa_model' ended with events '[BotUttered('by driving CS# Low while clock is idle', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1587140103.220427), <rasa.core.events.UserUtteranceReverted object at 0x7eff54cd3dd0>]'.
2020-04-17 18:15:03,226 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2020-04-17 18:15:03,231 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-17 18:15:03,232 [DEBUG]  Deleted lock for conversation 'ak'.
2020-04-17 18:15:28,584 [DEBUG]  Recreating tracker for id 'ak'
2020-04-17 18:15:28,608 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-17 18:15:28,612 [DEBUG]  Adding following selector key to message property: default
2020-04-17 18:15:28,612 [DEBUG]  Received user message 'what is the discription of CS# in hyperbus' with intent '{'name': 'affirm', 'confidence': 0.3417629599571228}' and entities '[]'
2020-04-17 18:15:28,613 [DEBUG]  Logged UserUtterance - tracker now has 19 events.
2020-04-17 18:15:28,615 [DEBUG]  Current tracker state [None, None, None, {}, {'intent_affirm': 1.0, 'prev_action_listen': 1.0}]
2020-04-17 18:15:28,615 [DEBUG]  There is no memorised next action
2020-04-17 18:15:28,625 [DEBUG]  NLU confidence 0.3417629599571228 is lower than NLU threshold 0.40. 
2020-04-17 18:15:28,628 [DEBUG]  Predicted next action using policy_3_FallbackPolicy
2020-04-17 18:15:28,629 [DEBUG]  Predicted next action 'action_faq_qa_model' with confidence 1.00.
2020-04-17 18:15:28,629 [DEBUG]  Calling action endpoint to run action 'action_faq_qa_model'.
2020-04-17 18:15:34,281 [DEBUG]  Action 'action_faq_qa_model' ended with events '[BotUttered('Low', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1587140134.2810345), <rasa.core.events.UserUtteranceReverted object at 0x7eff54cd35d0>]'.
2020-04-17 18:15:34,282 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2020-04-17 18:15:34,285 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-17 18:15:34,286 [DEBUG]  Deleted lock for conversation 'ak'.
2020-04-17 18:15:48,412 [DEBUG]  Recreating tracker for id 'ak'
2020-04-17 18:15:48,433 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-17 18:15:48,434 [DEBUG]  Adding following selector key to message property: default
2020-04-17 18:15:48,435 [DEBUG]  Received user message 'what is the discription of CS#' with intent '{'name': 'affirm', 'confidence': 0.4333054721355438}' and entities '[]'
2020-04-17 18:15:48,436 [DEBUG]  Logged UserUtterance - tracker now has 24 events.
2020-04-17 18:15:48,436 [DEBUG]  Current tracker state [None, None, None, {}, {'intent_affirm': 1.0, 'prev_action_listen': 1.0}]
2020-04-17 18:15:48,437 [DEBUG]  There is no memorised next action
2020-04-17 18:15:48,443 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-04-17 18:15:48,444 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-17 18:15:48,445 [DEBUG]  Predicted next action 'utter_happy' with confidence 0.95.
2020-04-17 18:15:48,452 [DEBUG]  Action 'utter_happy' ended with events '[BotUttered('Great, carry on!', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1587140148.4526517)]'.
2020-04-17 18:15:48,454 [DEBUG]  Current tracker state [None, None, {}, {'intent_affirm': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_happy': 1.0, 'intent_affirm': 1.0}]
2020-04-17 18:15:48,455 [DEBUG]  There is no memorised next action
2020-04-17 18:15:48,461 [DEBUG]  There is no mapped action for the predicted intent, 'affirm'.
2020-04-17 18:15:48,462 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-04-17 18:15:48,462 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-17 18:15:48,463 [DEBUG]  Predicted next action 'action_listen' with confidence 0.96.
2020-04-17 18:15:48,463 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-17 18:15:48,464 [DEBUG]  Deleted lock for conversation 'ak'.
2020-04-17 18:15:56,297 [DEBUG]  Recreating tracker for id 'ak'
2020-04-17 18:15:56,317 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-17 18:15:56,317 [DEBUG]  Adding following selector key to message property: default
2020-04-17 18:15:56,318 [DEBUG]  Received user message 'what is the discription of CS# in hyperbus' with intent '{'name': 'affirm', 'confidence': 0.3417629599571228}' and entities '[]'
2020-04-17 18:15:56,320 [DEBUG]  Logged UserUtterance - tracker now has 28 events.
2020-04-17 18:15:56,321 [DEBUG]  Current tracker state [None, {}, {'intent_affirm': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_happy': 1.0, 'intent_affirm': 1.0}, {'intent_affirm': 1.0, 'prev_action_listen': 1.0}]
2020-04-17 18:15:56,321 [DEBUG]  There is no memorised next action
2020-04-17 18:15:56,329 [DEBUG]  NLU confidence 0.3417629599571228 is lower than NLU threshold 0.40. 
2020-04-17 18:15:56,329 [DEBUG]  Predicted next action using policy_3_FallbackPolicy
2020-04-17 18:15:56,330 [DEBUG]  Predicted next action 'action_faq_qa_model' with confidence 1.00.
2020-04-17 18:15:56,330 [DEBUG]  Calling action endpoint to run action 'action_faq_qa_model'.
2020-04-17 18:16:02,031 [DEBUG]  Action 'action_faq_qa_model' ended with events '[BotUttered('Low', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1587140162.0311854), <rasa.core.events.UserUtteranceReverted object at 0x7eff00568c50>]'.
2020-04-17 18:16:02,032 [DEBUG]  Current tracker state [None, None, {}, {'intent_affirm': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_happy': 1.0, 'intent_affirm': 1.0}]
2020-04-17 18:16:02,033 [DEBUG]  There is no memorised next action
2020-04-17 18:16:02,043 [DEBUG]  There is no mapped action for the predicted intent, 'affirm'.
2020-04-17 18:16:02,045 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-04-17 18:16:02,046 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-17 18:16:02,046 [DEBUG]  Predicted next action 'action_listen' with confidence 0.96.
2020-04-17 18:16:02,047 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-17 18:16:02,048 [DEBUG]  Deleted lock for conversation 'ak'.
2020-04-17 18:19:40,144 [DEBUG]  Recreating tracker for id 'ak'
2020-04-17 18:19:43,147 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-17 18:19:43,148 [DEBUG]  Adding following selector key to message property: default
2020-04-17 18:19:43,148 [DEBUG]  Received user message 'what is the discription of CS# in hyperbus' with intent '{'name': 'affirm', 'confidence': 0.3417629599571228}' and entities '[]'
2020-04-17 18:19:43,174 [DEBUG]  Logged UserUtterance - tracker now has 33 events.
2020-04-17 18:19:43,179 [DEBUG]  Current tracker state [None, {}, {'intent_affirm': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_happy': 1.0, 'intent_affirm': 1.0}, {'intent_affirm': 1.0, 'prev_action_listen': 1.0}]
2020-04-17 18:19:43,250 [DEBUG]  There is no memorised next action
2020-04-17 18:19:43,353 [DEBUG]  NLU confidence 0.3417629599571228 is lower than NLU threshold 0.40. 
2020-04-17 18:19:43,356 [DEBUG]  Predicted next action using policy_3_FallbackPolicy
2020-04-17 18:19:43,357 [DEBUG]  Predicted next action 'action_faq_qa_model' with confidence 1.00.
2020-04-17 18:19:43,358 [DEBUG]  Calling action endpoint to run action 'action_faq_qa_model'.
2020-04-17 18:19:52,213 [DEBUG]  Action 'action_faq_qa_model' ended with events '[BotUttered('Low', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1587140392.213606), <rasa.core.events.UserUtteranceReverted object at 0x7eff00492590>]'.
2020-04-17 18:19:52,215 [DEBUG]  Current tracker state [None, None, {}, {'intent_affirm': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_happy': 1.0, 'intent_affirm': 1.0}]
2020-04-17 18:19:52,216 [DEBUG]  There is no memorised next action
2020-04-17 18:19:52,228 [DEBUG]  There is no mapped action for the predicted intent, 'affirm'.
2020-04-17 18:19:52,229 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-04-17 18:19:52,230 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-17 18:19:52,231 [DEBUG]  Predicted next action 'action_listen' with confidence 0.96.
2020-04-17 18:19:52,232 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-17 18:19:52,234 [DEBUG]  Deleted lock for conversation 'ak'.
2020-04-18 12:43:55,931 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-18 12:58:15,982 [ERROR]  Encountered an exception while running action 'action_faq_qa_model'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-04-18 12:59:07,041 [ERROR]  Encountered an exception while running action 'action_faq_qa_model'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-04-18 13:35:24,332 [ERROR]  Encountered an exception while running action 'action_faq_qa_model'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-04-18 13:45:52,887 [ERROR]  Encountered an exception while running action 'action_faq_qa_model'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
